DevOpsPartyGames/devopspartygames-web

- site-metadata.json
- src/pages/about.md
Signed-off-by: Matt Stratton <matt.stratton@gmail.com>
> Update about page and tweak nav

- src/pages/posts/Episode-1.md
Fixes #10
Signed-off-by: Matt Stratton <matt.stratton@gmail.com>
> Add timezone link to episode 1

- site-metadata.json
- src/pages/contact.md
- src/pages/faq.md
Connected to #13 
Adds links to the "propose a contestant" and "submit a prompt idea" in the footer, and also adds the preliminary FAQ page.
Also adds a Contact page with a Typeform that emails Matt and Jeremy.
> Add forms and FAQ page

- src/pages/posts/Episode-2.md
The date field doesn't show up anywhere so we can mess with it like this I think.
> Change episode 2 date for sorting reasons

- src/pages/faq.md
this should do - short and simple
> add new question to FAQ

- gatsby-config.js
- package-lock.json
- package.json
this fixes #17 by adding gatsby google analytics plugin (https://www.gatsbyjs.org/docs/adding-analytics/)
> add gatsby-plugin-google-analytics

- src/components/SectionPosts.js
- src/pages/posts/Episode-1.md
- src/pages/posts/Episode-2.md
- src/pages/posts/Episode-3.md
- src/pages/posts/Episode-4.md
- src/pages/posts/Episode-5.md
> Update sort order for episodes

- src/pages/posts/Episode-5.md
add q and pete to all stars page
> add two players

- netlify.toml
> Make netlify do CDN things

- site-metadata.json
> Add thought leaderboard to footer nav

- netlify.toml
- site-metadata.json
- src/pages/faq.md
> Add new airtable forms

- static/episode.md
This is just adding a markdown file to the `/static` directory that can be used for creating new episodes (for copy-paste purposes)
Fixes #105 
> Add starter template for episode files

- gatsby-config.js
- package-lock.json
- package.json
> Add sitemap plugin

- src/sass/imports/_custom.scss
> Remove border bottom from player twitter

- src/templates/episode.js
> Fix twitch link on episode page

- package-lock.json
- package.json
- src/components/ListOverallScores.js
- src/components/ListSeasonOneScores.js
- src/components/ListSeasonTwoScores.js
- src/html.js
- src/templates/thought-leaderboard.js
> Add tabs to leaderboard

- site-metadata.json
Video link now points to the new YouTube channel
> Update video link

- data/seasons/seasons.json
- gatsby-node.js
- src/components/ListSeasonThreeScores.js
- src/components/ShowSeasonThreeLeaderboardRank.js
- src/hooks/use-season-three-top-player.js
- src/templates/person.js
- src/templates/thought-leaderboard.js
> Update for season 3 scores

- data/episodes/episodes.json
Do not merge until youtube is finished processing
> Add video for s03e01

- data/episodes/episodes.json
Signed-off-by: Matt Stratton <matt.stratton@gmail.com>
> Add date for s03e02
